<?php

declare(strict_types=1);

namespace Sabri\File26\KnowledgeGraph;

use DateTimeImmutable;
use DateTimeZone;
use Sabri\File26\Domain\SearchDocument;
use Sabri\File26\Search\AudienceContext;
use Sabri\File26\Search\EligibilityEvaluator;
use Sabri\File26\Support\InvariantViolation;
use wpdb;

final class GraphEdge
{
    public const TYPES=['author-of','lesson-about','remedy-related','doctor-published','book-chapter','video-explains','research-supports','research-contradicts','post-references','pdf-authored-by','clinic-operated-by','topic-related','corrects','retracts'];public const STATES=['active','corrected','retracted'];
    public function __construct(private readonly string $edgeId,private readonly string $fromKey,private readonly string $toKey,private readonly string $type,private readonly string $sourceOwner,private readonly string $sourceVersion,private readonly string $evidenceUrl,private readonly string $state,private readonly bool $public,private readonly array $requiredCapabilities,private readonly DateTimeImmutable $updatedAt)
    {if(!preg_match('/^[a-f0-9]{64}$/',$edgeId)||trim($fromKey)===''||trim($toKey)===''||$fromKey===$toKey||strlen($fromKey)>292||strlen($toKey)>292||!in_array($type,self::TYPES,true)||!preg_match('/^[a-z][a-z0-9._-]{2,99}$/',$sourceOwner)||trim($sourceVersion)===''||strlen($sourceVersion)>100||!filter_var($evidenceUrl,FILTER_VALIDATE_URL)||!in_array($state,self::STATES,true))throw new InvariantViolation('Knowledge graph edge metadata is invalid.');$parts=parse_url($evidenceUrl);if(!is_array($parts)||($parts['scheme']??'')!=='https'||isset($parts['user'])||isset($parts['pass']))throw new InvariantViolation('Knowledge graph evidence URLs must be credential-free HTTPS URLs.');if(!array_is_list($requiredCapabilities)||count($requiredCapabilities)>20||count($requiredCapabilities)!==count(array_unique($requiredCapabilities)))throw new InvariantViolation('Graph edge capabilities must be bounded and unique.');foreach($requiredCapabilities as $capability)if(!is_string($capability)||!preg_match('/^[a-z][a-z0-9_]{2,99}$/',$capability))throw new InvariantViolation('Graph edge capability is invalid.');if($public&&$requiredCapabilities!==[])throw new InvariantViolation('Public graph edges cannot require private capabilities.');}
    public static function create(string $fromKey,string $toKey,string $type,string $sourceOwner,string $sourceVersion,string $evidenceUrl,bool $public=true,array $requiredCapabilities=[]):self{$id=hash('sha256',implode("\0",[$fromKey,$toKey,$type,$sourceOwner,$sourceVersion]));return new self($id,$fromKey,$toKey,$type,$sourceOwner,$sourceVersion,$evidenceUrl,'active',$public,$requiredCapabilities,new DateTimeImmutable('now'));}
    public function edgeId():string{return $this->edgeId;}public function fromKey():string{return $this->fromKey;}public function toKey():string{return $this->toKey;}public function type():string{return $this->type;}public function sourceOwner():string{return $this->sourceOwner;}public function sourceVersion():string{return $this->sourceVersion;}public function evidenceUrl():string{return $this->evidenceUrl;}public function state():string{return $this->state;}public function isPublic():bool{return $this->public;}public function requiredCapabilities():array{return $this->requiredCapabilities;}public function updatedAt():DateTimeImmutable{return $this->updatedAt;}public function toArray():array{return ['edge_id'=>$this->edgeId,'from_key'=>$this->fromKey,'to_key'=>$this->toKey,'type'=>$this->type,'source_owner'=>$this->sourceOwner,'source_version'=>$this->sourceVersion,'evidence_url'=>$this->evidenceUrl,'state'=>$this->state,'public'=>$this->public,'required_capabilities'=>$this->requiredCapabilities,'updated_at'=>$this->updatedAt->format(DATE_ATOM)];}
}

final class GraphTraversalResult
{
    public function __construct(private readonly string $startKey,private readonly array $nodes,private readonly array $edges,private readonly bool $truncated){if(trim($startKey)===''||!array_is_list($nodes)||!array_is_list($edges)||count($nodes)>500||count($edges)>1000)throw new InvariantViolation('Knowledge graph traversal result is invalid or unbounded.');}
    public function toArray():array{return ['start_key'=>$this->startKey,'nodes'=>array_map(static fn(SearchDocument $node):array=>$node->toArray(),$this->nodes),'edges'=>array_map(static fn(GraphEdge $edge):array=>$edge->toArray(),$this->edges),'truncated'=>$this->truncated];}
}

final class KnowledgeGraph
{
    private array $nodes=[];private array $edges=[];private array $outgoing=[];public function __construct(private readonly EligibilityEvaluator $eligibility=new EligibilityEvaluator()){}
    public function putNode(SearchDocument $document):void{$this->nodes[$document->canonicalKey()]=$document;}
    public function putEdge(GraphEdge $edge):void{if(!isset($this->nodes[$edge->fromKey()],$this->nodes[$edge->toKey()]))throw new InvariantViolation('Knowledge graph edges require existing endpoint nodes.');$fromDomain=explode(':',$edge->fromKey(),2)[0]??'';if($edge->sourceOwner()!==$fromDomain&&$edge->sourceOwner()!=='file26-curated')throw new InvariantViolation('Knowledge graph edge source owner must own the source endpoint or be the approved curator.');$this->edges[$edge->edgeId()]=$edge;$this->outgoing[$edge->fromKey()]??=[];if(!in_array($edge->edgeId(),$this->outgoing[$edge->fromKey()],true)){$this->outgoing[$edge->fromKey()][]=$edge->edgeId();sort($this->outgoing[$edge->fromKey()]);}}
    public function traverse(string $startKey,AudienceContext $audience,array $allowedTypes,int $maximumDepth=2,int $maximumDegree=25,int $maximumNodes=200):GraphTraversalResult
    {if(!isset($this->nodes[$startKey]))throw new InvariantViolation('Knowledge graph start node was not found.');if(!array_is_list($allowedTypes)||$allowedTypes===[]||count($allowedTypes)>count(GraphEdge::TYPES))throw new InvariantViolation('Knowledge graph allowed edge types are invalid.');foreach($allowedTypes as $type)if(!is_string($type)||!in_array($type,GraphEdge::TYPES,true))throw new InvariantViolation('Knowledge graph traversal requested an unsupported edge type.');if($maximumDepth<1||$maximumDepth>4||$maximumDegree<1||$maximumDegree>100||$maximumNodes<2||$maximumNodes>500)throw new InvariantViolation('Knowledge graph traversal bounds are unsafe.');$start=$this->nodes[$startKey];if(!$this->eligibility->canView($start,$audience))throw new InvariantViolation('Knowledge graph start node is not visible to this audience.');$queue=[[$startKey,0]];$visited=[$startKey=>true];$nodes=[$start];$edges=[];$truncated=false;while($queue!==[]){[$key,$depth]=array_shift($queue);if($depth>=$maximumDepth)continue;$edgeIds=array_slice($this->outgoing[$key]??[],0,$maximumDegree);if(count($this->outgoing[$key]??[])>$maximumDegree)$truncated=true;foreach($edgeIds as $edgeId){$edge=$this->edges[$edgeId];if($edge->state()!=='active'||!in_array($edge->type(),$allowedTypes,true)||!$this->edgeVisible($edge,$audience))continue;$target=$this->nodes[$edge->toKey()]??null;if(!$target instanceof SearchDocument||!$this->eligibility->canView($target,$audience))continue;$edges[$edge->edgeId()]=$edge;if(!isset($visited[$target->canonicalKey()])){$visited[$target->canonicalKey()]=true;$nodes[]=$target;$queue[]=[$target->canonicalKey(),$depth+1];if(count($nodes)>=$maximumNodes){$truncated=true;break 2;}}}}return new GraphTraversalResult($startKey,$nodes,array_values($edges),$truncated);}
    private function edgeVisible(GraphEdge $edge,AudienceContext $audience):bool{if($edge->isPublic())return true;if(!$audience->isAuthenticated())return false;foreach($edge->requiredCapabilities() as $capability)if(!$audience->hasCapability($capability))return false;return true;}
}

final class WordPressGraphStore
{
    private readonly string $table;public function __construct(private readonly wpdb $db){$this->table=$db->prefix.'s26_graph_edges';}
    public function save(GraphEdge $edge):void{$payload=json_encode($edge->toArray(),JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$hash=hash('sha256',$payload);$written=$this->db->query($this->db->prepare("INSERT INTO {$this->table} (edge_id,from_key,to_key,edge_type,state,source_owner,source_version,payload,payload_hash,updated_at) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) ON DUPLICATE KEY UPDATE state=VALUES(state),source_version=VALUES(source_version),payload=VALUES(payload),payload_hash=VALUES(payload_hash),updated_at=VALUES(updated_at)",$edge->edgeId(),$edge->fromKey(),$edge->toKey(),$edge->type(),$edge->state(),$edge->sourceOwner(),$edge->sourceVersion(),$payload,$hash,$edge->updatedAt()->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s.u')));if($written===false)throw new InvariantViolation('Knowledge graph edge persistence failed.');}
    public function outgoing(string $fromKey,int $limit=100):array{if(trim($fromKey)===''||strlen($fromKey)>292||$limit<1||$limit>500)throw new InvariantViolation('Knowledge graph read request is invalid.');$rows=$this->db->get_results($this->db->prepare("SELECT payload,payload_hash FROM {$this->table} WHERE from_key=%s AND state='active' ORDER BY edge_id LIMIT %d",$fromKey,$limit),ARRAY_A);$result=[];foreach(is_array($rows)?$rows:[] as $row){$payload=(string)$row['payload'];if(!hash_equals((string)$row['payload_hash'],hash('sha256',$payload)))throw new InvariantViolation('Knowledge graph stored payload integrity check failed.');$decoded=json_decode($payload,true,512,JSON_THROW_ON_ERROR);if(!is_array($decoded))throw new InvariantViolation('Knowledge graph payload is invalid.');$result[]=$decoded;}return$result;}
}
