<?php

declare(strict_types=1);

namespace Sabri\File26\Taxonomy;

use DateTimeImmutable;
use DateTimeZone;
use Sabri\File26\Query\UnicodeNormalizer;
use Sabri\File26\Support\InvariantViolation;
use wpdb;

final class TaxonomyTerm
{
    public const STATES=['draft','approved','active','deprecated','merged','split','retired'];
    public function __construct(private readonly string $termId,private readonly int $version,private readonly array $preferredLabels,private readonly array $aliases,private readonly array $parentIds,private readonly array $relatedIds,private readonly string $definition,private readonly string $ownerKey,private readonly string $state,private readonly ?string $redirectTermId=null,private readonly DateTimeImmutable $updatedAt=new DateTimeImmutable('2026-08-04T00:00:00+00:00'))
    {
        if(!preg_match('/^[a-z][a-z0-9._-]{2,99}$/',$termId)||$version<1||$version>PHP_INT_MAX||$preferredLabels===[]||count($preferredLabels)>20||!in_array($state,self::STATES,true)||!preg_match('/^[a-z][a-z0-9._-]{2,99}$/',$ownerKey)||strlen($definition)>20000)throw new InvariantViolation('Taxonomy term metadata is invalid.');
        foreach($preferredLabels as $locale=>$label)if(!is_string($locale)||!preg_match('/^[A-Za-z]{2,3}(?:[-_][A-Za-z0-9]{2,8})*$/',$locale)||!is_string($label)||trim($label)===''||strlen($label)>500)throw new InvariantViolation('Taxonomy preferred label is invalid.');
        foreach($aliases as $locale=>$values){if(!is_string($locale)||!array_is_list($values)||count($values)>100||count($values)!==count(array_unique($values)))throw new InvariantViolation('Taxonomy alias list is invalid.');foreach($values as $value)if(!is_string($value)||trim($value)===''||strlen($value)>500)throw new InvariantViolation('Taxonomy alias is invalid.');}
        foreach([$parentIds,$relatedIds] as $ids){if(!array_is_list($ids)||count($ids)>100||count($ids)!==count(array_unique($ids)))throw new InvariantViolation('Taxonomy relationships must be bounded and unique.');foreach($ids as $id)if(!is_string($id)||!preg_match('/^[a-z][a-z0-9._-]{2,99}$/',$id)||$id===$termId)throw new InvariantViolation('Taxonomy relationship ID is invalid.');}
        if(in_array($state,['merged','split'],true)&&($redirectTermId===null||$redirectTermId===$termId))throw new InvariantViolation('Merged or split taxonomy term requires a distinct redirect target.');if(!in_array($state,['merged','split'],true)&&$redirectTermId!==null)throw new InvariantViolation('Only merged or split taxonomy terms may redirect.');
    }
    public function termId():string{return $this->termId;}public function version():int{return $this->version;}public function preferredLabels():array{return $this->preferredLabels;}public function aliases():array{return $this->aliases;}public function parentIds():array{return $this->parentIds;}public function relatedIds():array{return $this->relatedIds;}public function definition():string{return $this->definition;}public function ownerKey():string{return $this->ownerKey;}public function state():string{return $this->state;}public function redirectTermId():?string{return $this->redirectTermId;}public function updatedAt():DateTimeImmutable{return $this->updatedAt;}
    public function withRelationships(array $parents,array $related,int $version,DateTimeImmutable $at):self{return new self($this->termId,$version,$this->preferredLabels,$this->aliases,$parents,$related,$this->definition,$this->ownerKey,$this->state,$this->redirectTermId,$at);}public function mergedInto(string $target,int $version,DateTimeImmutable $at):self{return new self($this->termId,$version,$this->preferredLabels,$this->aliases,$this->parentIds,$this->relatedIds,$this->definition,$this->ownerKey,'merged',$target,$at);}public function toArray():array{return ['term_id'=>$this->termId,'version'=>$this->version,'preferred_labels'=>$this->preferredLabels,'aliases'=>$this->aliases,'parent_ids'=>$this->parentIds,'related_ids'=>$this->relatedIds,'definition'=>$this->definition,'owner_key'=>$this->ownerKey,'state'=>$this->state,'redirect_term_id'=>$this->redirectTermId,'updated_at'=>$this->updatedAt->format(DATE_ATOM)];}
}

final class TaxonomyRegistry
{
    private array $terms=[];private UnicodeNormalizer $normalizer;public function __construct(?UnicodeNormalizer $normalizer=null){$this->normalizer=$normalizer??new UnicodeNormalizer();}
    public function register(TaxonomyTerm $term):void{$current=$this->terms[$term->termId()]??null;if($current instanceof TaxonomyTerm&&$term->version()!==$current->version()+1)throw new InvariantViolation('Taxonomy version must advance exactly by one.');$this->assertReferencesExist($term);$candidate=$this->terms;$candidate[$term->termId()]=$term;$this->assertNoCycles($candidate);$this->assertNoActiveLabelCollisions($candidate);$this->terms=$candidate;}
    public function get(string $id):TaxonomyTerm{$term=$this->terms[$id]??null;if(!$term instanceof TaxonomyTerm)throw new InvariantViolation('Unknown taxonomy term.');return $term;}
    public function all():array{$terms=$this->terms;ksort($terms);return array_values($terms);}
    public function previewMerge(string $sourceId,string $targetId):array{$source=$this->get($sourceId);$target=$this->get($targetId);if($sourceId===$targetId||!in_array($source->state(),['approved','active','deprecated'],true)||!in_array($target->state(),['approved','active'],true))throw new InvariantViolation('Taxonomy merge is invalid for these terms.');$affected=[];foreach($this->terms as $term)if(in_array($sourceId,$term->parentIds(),true)||in_array($sourceId,$term->relatedIds(),true))$affected[]=$term->termId();sort($affected);return ['source'=>$sourceId,'target'=>$targetId,'affected_terms'=>$affected,'source_version'=>$source->version(),'target_version'=>$target->version()];}
    public function applyMerge(array $preview,DateTimeImmutable $at):void
    {
        foreach(['source','target','affected_terms','source_version','target_version'] as $key)if(!array_key_exists($key,$preview))throw new InvariantViolation('Taxonomy merge preview is incomplete.');$source=$this->get((string)$preview['source']);$target=$this->get((string)$preview['target']);if($source->version()!==(int)$preview['source_version']||$target->version()!==(int)$preview['target_version'])throw new InvariantViolation('Taxonomy merge preview is stale.');$candidate=$this->terms;$candidate[$source->termId()]=$source->mergedInto($target->termId(),$source->version()+1,$at);foreach($candidate as $id=>$term){if($id===$source->termId())continue;$parents=array_values(array_unique(array_map(static fn(string $value):string=>$value===$source->termId()?$target->termId():$value,$term->parentIds())));$related=array_values(array_unique(array_map(static fn(string $value):string=>$value===$source->termId()?$target->termId():$value,$term->relatedIds())));if($parents!==$term->parentIds()||$related!==$term->relatedIds())$candidate[$id]=$term->withRelationships($parents,$related,$term->version()+1,$at);}$this->assertNoCycles($candidate);$this->assertNoActiveLabelCollisions($candidate);$this->terms=$candidate;
    }
    private function assertReferencesExist(TaxonomyTerm $term):void{foreach([...$term->parentIds(),...$term->relatedIds()] as $id)if(!isset($this->terms[$id]))throw new InvariantViolation('Taxonomy relationship references an unknown term.');if($term->redirectTermId()!==null&&!isset($this->terms[$term->redirectTermId()]))throw new InvariantViolation('Taxonomy redirect target is unknown.');}
    private function assertNoCycles(array $terms):void{$visited=[];$active=[];$walk=function(string $id)use(&$walk,&$visited,&$active,$terms):void{if(isset($active[$id]))throw new InvariantViolation('Taxonomy parent cycle is forbidden.');if(isset($visited[$id]))return;$active[$id]=true;foreach($terms[$id]->parentIds() as $parent)$walk($parent);unset($active[$id]);$visited[$id]=true;};foreach(array_keys($terms) as $id)$walk($id);}
    private function assertNoActiveLabelCollisions(array $terms):void{$seen=[];foreach($terms as $term){if(!in_array($term->state(),['approved','active'],true))continue;foreach($term->preferredLabels() as $locale=>$label){foreach([$label,...($term->aliases()[$locale]??[])] as $value){$key=strtolower(str_replace('_','-',$locale)).'|'.$this->normalizer->normalizeForSearch($value);if(isset($seen[$key])&&$seen[$key]!==$term->termId())throw new InvariantViolation('Active taxonomy labels and aliases must be unambiguous.');$seen[$key]=$term->termId();}}}}
}

final class WordPressTaxonomyStore
{
    private readonly string $table;public function __construct(private readonly wpdb $db){$this->table=$db->prefix.'s26_taxonomy_terms';}
    public function save(TaxonomyTerm $term,?int $expectedVersion=null):void{$payload=json_encode($term->toArray(),JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$hash=hash('sha256',$payload);$this->db->query('START TRANSACTION');try{$current=$this->db->get_row($this->db->prepare("SELECT version FROM {$this->table} WHERE term_id=%s FOR UPDATE",$term->termId()),ARRAY_A);$currentVersion=is_array($current)?(int)$current['version']:0;if($expectedVersion!==null&&$currentVersion!==$expectedVersion)throw new InvariantViolation('Taxonomy optimistic-lock version mismatch.');if($term->version()!==$currentVersion+1)throw new InvariantViolation('Taxonomy persistent version must advance exactly by one.');$written=$this->db->query($this->db->prepare("INSERT INTO {$this->table} (term_id,version,state,owner_key,redirect_term_id,payload,payload_hash,updated_at) VALUES (%s,%d,%s,%s,%s,%s,%s,%s) ON DUPLICATE KEY UPDATE version=VALUES(version),state=VALUES(state),owner_key=VALUES(owner_key),redirect_term_id=VALUES(redirect_term_id),payload=VALUES(payload),payload_hash=VALUES(payload_hash),updated_at=VALUES(updated_at)",$term->termId(),$term->version(),$term->state(),$term->ownerKey(),$term->redirectTermId(),$payload,$hash,$term->updatedAt()->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s.u')));if($written===false)throw new InvariantViolation('Taxonomy persistent write failed.');$this->db->query('COMMIT');}catch(\Throwable $e){$this->db->query('ROLLBACK');throw $e;}}
    public function get(string $termId):TaxonomyTerm{$row=$this->db->get_row($this->db->prepare("SELECT payload,payload_hash FROM {$this->table} WHERE term_id=%s",$termId),ARRAY_A);if(!is_array($row)||!hash_equals((string)$row['payload_hash'],hash('sha256',(string)$row['payload'])))throw new InvariantViolation('Taxonomy term is missing or corrupt.');return $this->hydrate(json_decode((string)$row['payload'],true,32,JSON_THROW_ON_ERROR));}
    public function rows(int $limit=1000):array{if($limit<1||$limit>5000)throw new InvariantViolation('Taxonomy read limit is invalid.');$rows=$this->db->get_results($this->db->prepare("SELECT term_id,version,state,owner_key,redirect_term_id,payload_hash,updated_at FROM {$this->table} ORDER BY term_id LIMIT %d",$limit),ARRAY_A);return is_array($rows)?$rows:[];}
    private function hydrate(array $data):TaxonomyTerm{return new TaxonomyTerm((string)$data['term_id'],(int)$data['version'],$data['preferred_labels'],$data['aliases'],$data['parent_ids'],$data['related_ids'],(string)$data['definition'],(string)$data['owner_key'],(string)$data['state'],$data['redirect_term_id']===null?null:(string)$data['redirect_term_id'],new DateTimeImmutable((string)$data['updated_at']));}
}
