<?php
namespace Sabri\File26;
defined( 'ABSPATH' ) || exit;

/** Federated search with production-lane isolation and truthful partial-state reporting. */
final class Search {
	private $normalizer;
	private $ranking;
	private $security;
	private $connectors;

	public function __construct( Normalizer $normalizer, Ranking $ranking, Security $security, Connectors $connectors ) {
		$this->normalizer=$normalizer;$this->ranking=$ranking;$this->security=$security;$this->connectors=$connectors;
	}

	public function run( array $request ) {
		global $wpdb;
		$trace=$this->security->trace_id();$started_at=microtime(true);
		if(!DB::setting('activated',false)||!DB::setting('public_search_enabled',true)){return new \WP_Error('file26_not_activated','Search is not yet activated. Approved connector and staging gates are required.',array('status'=>503,'trace_id'=>$trace));}
		$query=$this->security->sanitize_query(isset($request['q'])?$request['q']:'');$locale=isset($request['locale'])?substr(sanitize_text_field($request['locale']),0,20):determine_locale();
		$limit=isset($request['limit'])?(int)$request['limit']:(int)DB::setting('results_per_page',20);$limit=max(1,min((int)DB::setting('max_results_per_page',30),$limit));$filters=$this->sanitize_filters(isset($request['filters'])?$request['filters']:array());
		$policy_version=$this->ranking->policy_version();$policy_error=$this->ranking->last_error();if(is_wp_error($policy_error)){return new \WP_Error($policy_error->get_error_code(),$policy_error->get_error_message(),array('status'=>503,'trace_id'=>$trace));}
		$audience=$this->security->audience();$entitlements=array_values(array_unique(array_map('sanitize_key',(array)$audience['entitlements'])));$roles=array_values(array_unique(array_map('sanitize_key',(array)$audience['roles'])));sort($entitlements,SORT_STRING);sort($roles,SORT_STRING);
		$audience_fingerprint=hash('sha256',wp_json_encode(array('user_id'=>!empty($audience['authenticated'])?(int)$audience['user_id']:0,'authenticated'=>!empty($audience['authenticated']),'valid'=>!empty($audience['valid']),'is_minor'=>!empty($audience['is_minor']),'guardian_verified'=>!empty($audience['guardian_verified']),'entitlements'=>$entitlements,'roles'=>$roles)));
		$cursor_context=hash('sha256',wp_json_encode(array('q'=>$this->normalizer->normalize($query),'locale'=>$locale,'filters'=>$filters,'limit'=>$limit,'policy'=>$policy_version,'audience'=>$audience_fingerprint)));
		$offset=0;if(!empty($request['cursor'])){$cursor=$this->security->verify_cursor($request['cursor']);if(!$cursor||empty($cursor['p'])||empty($cursor['h'])||$cursor['p']!==$policy_version||!hash_equals($cursor_context,(string)$cursor['h'])){return new \WP_Error('file26_invalid_cursor','The result cursor is invalid or expired for the current eligibility context.',array('status'=>400,'trace_id'=>$trace));}$offset=max(0,min(100000,(int)$cursor['o']));}
		if(!$this->security->rate_limit('search|'.$this->security->client_bucket(),120,60)){return new \WP_Error('file26_rate_limited','Too many search requests. Please retry shortly.',array('status'=>429,'trace_id'=>$trace));}

		$sensitive_query=$this->security->contains_sensitive_query($query);$cache_context=array('query'=>$query,'locale'=>$locale,'filters'=>$filters,'policy'=>$policy_version);
		$public_cache=empty($audience['authenticated'])&&empty($filters['availability'])&&!$sensitive_query&&(bool)apply_filters('sabri_file26_revocation_cache_purge_ready',false,'object_cache',$cache_context)&&(bool)apply_filters('sabri_file26_object_cache_allowed',false,$cache_context);
		$cache_key='search:'.hash('sha256',wp_json_encode(array('q'=>$query,'locale'=>$locale,'filters'=>$filters,'offset'=>$offset,'limit'=>$limit,'policy'=>$policy_version)));
		if($public_cache){$cached=wp_cache_get($cache_key,'sabri_file26');if(is_array($cached)){$this->record_operational_metric('search_cache_hit',$locale,1,0);$cached['trace_id']=$trace;return $cached;}$this->record_operational_metric('search_cache_miss',$locale,1,0);}

		$where=array("d.state IN ('published','active','corrected','retracted')","d.safety_class NOT IN ('blocked','restricted')");$args=array();
		if(empty($audience['authenticated'])||empty($audience['valid'])){$where[]="d.visibility='public'";}else{$where[]="d.visibility IN ('public','members','entitled','minor_guarded')";}
		if($locale){$where[]='(d.locale=%s OR d.locale=%s OR d.locale=%s)';$args[]=$locale;$args[]=substr($locale,0,2);$args[]='und';}
		$filter_map=array('entity_type'=>'d.entity_type','country'=>'d.country','location'=>'d.location','availability'=>'d.availability','connector'=>'d.connector_slug','domain'=>'d.domain_name','language'=>'d.locale');foreach($filter_map as $key=>$column){if(!empty($filters[$key])){$where[]="$column=%s";$args[]=$filters[$key];}}
		if(!empty($filters['author'])){$where[]='d.author_key=%s';$args[]=$filters['author'];}
		if(!empty($filters['topic'])){$where[]="(d.topic_ids LIKE %s OR EXISTS (SELECT 1 FROM ".DB::table('classifications')." fc WHERE fc.object_key=d.canonical_key AND fc.term_uuid=%s AND fc.status IN ('approved','corrected')))";$args[]='%"'.$wpdb->esc_like($filters['topic']).'"%';$args[]=$filters['topic'];}
		if(!empty($filters['date_from'])){$where[]='d.freshness_at >= %s';$args[]=$filters['date_from'].' 00:00:00';}if(!empty($filters['date_to'])){$where[]='d.freshness_at <= %s';$args[]=$filters['date_to'].' 23:59:59';}
		$search_terms=$this->normalizer->retrieval_terms($query);$phrases=$this->normalizer->phrases($query);if($search_terms||$phrases){$search_parts=array();foreach(array_merge($phrases,$search_terms) as $term){$search_parts[]='(d.normalized_title LIKE %s OR d.normalized_body LIKE %s)';$like='%'.$wpdb->esc_like($term).'%';$args[]=$like;$args[]=$like;}$where[]='('.implode(' OR ',$search_parts).')';}

		$documents=DB::table('documents');$connectors=DB::table('connectors');$batch_size=max(50,min(500,(int)DB::setting('search_scan_batch',250)));$max_scan=max($batch_size,min(50000,(int)DB::setting('max_candidate_scan',5000)));$scan_offset=0;$eligible=array();$scan_limit_hit=false;$order=''===$query?'d.freshness_at DESC,d.canonical_key ASC':'d.canonical_key ASC';
		$base_sql="SELECT d.* FROM $documents d INNER JOIN $connectors c ON c.slug=d.connector_slug AND c.status='active' WHERE ".implode(' AND ',$where)." ORDER BY $order";
		while($scan_offset<$max_scan){$sql=$base_sql.' LIMIT %d OFFSET %d';$query_args=array_merge($args,array($batch_size,$scan_offset));$rows=$wpdb->get_results($wpdb->prepare($sql,$query_args),ARRAY_A);if(null===$rows&&!empty($wpdb->last_error)){return new \WP_Error('file26_search_read_failed','Search candidates could not be read safely.',array('status'=>503,'trace_id'=>$trace));}if(!$rows){break;}foreach($rows as $row){$row=$this->hydrate_row($row);if(!$this->eligible_row($row,$audience,$filters,$locale)){continue;}if($query&&!$this->ranking->matches_query($row,$query)){continue;}$eligible[$row['canonical_key']]=$row;}$scan_offset+=count($rows);if(count($rows)<$batch_size){break;}}
		if($scan_offset>=$max_scan){$scan_limit_hit=true;}

		$retrieval=array('lexical'=>true,'semantic'=>'not_configured','semantic_candidates'=>0,'deduplicated'=>0);
		$semantic=$this->semantic_candidates($query,$locale,$filters,$audience,$sensitive_query,$trace);
		if(is_wp_error($semantic)){return $semantic;}
		if(!empty($semantic['status'])){$retrieval['semantic']=$semantic['status'];}
		if(!empty($semantic['rows'])){foreach($semantic['rows'] as $row){$eligible[$row['canonical_key']]=$row;}$retrieval['semantic_candidates']=count($semantic['rows']);}

		$eligible=array_values($eligible);$eligible=$this->apply_graph_relationship_scores($eligible);if(is_wp_error($eligible)){return $eligible;}
		$ranked=$this->ranking->sort_and_diversify($eligible,$query,count($eligible));$before_dedupe=count($ranked);$ranked=$this->dedupe_ranked($ranked);$retrieval['deduplicated']=max(0,$before_dedupe-count($ranked));
		if(!empty($filters['sort'])&&in_array($filters['sort'],array('newest','oldest','authority'),true)){usort($ranked,static function($a,$b)use($filters){if('authority'===$filters['sort']){return(float)$a['authority_score']===(float)$b['authority_score']?strcmp($a['canonical_key'],$b['canonical_key']):((float)$a['authority_score']>(float)$b['authority_score']?-1:1);}$at=!empty($a['freshness_at'])?strtotime($a['freshness_at'].' UTC'):0;$bt=!empty($b['freshness_at'])?strtotime($b['freshness_at'].' UTC'):0;if($at===$bt){return strcmp($a['canonical_key'],$b['canonical_key']);}return'oldest'===$filters['sort']?$at<=>$bt:$bt<=>$at;});}
		$page_rows=array_slice($ranked,$offset,$limit);$has_more=count($ranked)>($offset+$limit);$results=array();foreach($page_rows as $row){$results[]=$this->to_result($row,$query);}
		$partial=$this->connectors->degraded_domains();if($scan_limit_hit){$partial[]=array('connector'=>'*','owner_file'=>'File 26','status'=>'bounded','health'=>'scan_limit','last_health'=>null);}if('degraded'===$retrieval['semantic']){$partial[]=array('connector'=>'semantic-provider','owner_file'=>'File 26','status'=>'degraded','health'=>'keyword_fallback','last_health'=>null);}
		$response=array('contract_version'=>SABRI_FILE26_CONTRACT_VERSION,'query'=>$query,'query_normalized'=>$this->normalizer->normalize($query),'policy_version'=>$policy_version,'results'=>$results,'facets'=>$this->facets_from_rows($eligible),'next_cursor'=>$has_more?$this->security->sign_cursor(array('o'=>$offset+$limit,'p'=>$policy_version,'h'=>$cursor_context)):null,'partial'=>(bool)$partial,'partial_domains'=>$partial,'personalized'=>false,'scanned_candidates'=>$scan_offset,'eligible_candidates'=>count($eligible),'retrieval'=>$retrieval,'trace_id'=>$trace);
		if(DB::setting('telemetry_enabled',true)){$metric=$this->record_metric($query,$locale,count($results),$trace,(microtime(true)-$started_at)*1000);$response['telemetry_status']=is_wp_error($metric)?'degraded':'recorded';}
		if($public_cache){$ttl=max(1,min(300,(int)apply_filters('sabri_file26_object_cache_ttl',60,$cache_context)));wp_cache_set($cache_key,$response,'sabri_file26',$ttl);}
		return $response;
	}

	public function suggest($prefix,$locale=null,$limit=8){global $wpdb;if(!DB::setting('activated',false)||!DB::setting('public_search_enabled',true)){return array();}$prefix=$this->security->sanitize_query($prefix);if(!$this->normalizer->prefix_is_safe($prefix)||$this->security->contains_sensitive_query($prefix)){return array();}if(!$this->security->rate_limit('suggest|'.$this->security->client_bucket(),180,60)){return array();}$normalized=$this->normalizer->normalize($prefix);$like=$wpdb->esc_like($normalized).'%';$table=DB::table('documents');$connector_table=DB::table('connectors');$locale=$locale?substr(sanitize_text_field($locale),0,20):determine_locale();$limit=max(1,min(10,(int)$limit));$rows=$wpdb->get_results($wpdb->prepare("SELECT d.* FROM $table d INNER JOIN $connector_table c ON c.slug=d.connector_slug AND c.status='active' WHERE d.state IN ('published','active','corrected') AND d.visibility='public' AND d.safety_class NOT IN ('blocked','restricted') AND d.normalized_title LIKE %s AND (d.locale=%s OR d.locale=%s OR d.locale='und') ORDER BY d.authority_score DESC,d.quality_score DESC,d.title ASC LIMIT %d",$like,$locale,substr($locale,0,2),min(50,$limit*5)),ARRAY_A);if(null===$rows&&!empty($wpdb->last_error)){return new \WP_Error('file26_suggest_read_failed','Suggestions could not be read safely.',array('status'=>503));}$output=array();$audience=array('authenticated'=>false,'valid'=>true,'is_minor'=>false,'guardian_verified'=>false,'entitlements'=>array(),'roles'=>array(),'user_id'=>0);foreach((array)$rows as $row){$row=$this->hydrate_row($row);if(!$this->connectors->can_view($row['connector_slug'],$row,$audience)||in_array($row['safety_class'],array('blocked','restricted'),true)){continue;}$output[]=array('key'=>$row['canonical_key'],'label'=>$row['title'],'entity_type'=>$row['entity_type'],'url'=>$row['canonical_url']);if(count($output)>=$limit){break;}}return$output;}

	private function semantic_candidates($query,$locale,array $filters,array $audience,$sensitive,$trace){
		global $wpdb;$out=array('status'=>'not_configured','rows'=>array());if(''===$query||$sensitive){$out['status']=$sensitive?'disabled_sensitive':'not_applicable';return$out;}
		$approved=(bool)apply_filters('sabri_file26_semantic_provider_approved',false,array('locale'=>$locale,'filters'=>$filters));if(!$approved){return$out;}
		$request=array('query'=>$query,'query_normalized'=>$this->normalizer->normalize($query),'locale'=>$locale,'filters'=>$filters,'limit'=>max(20,min(200,(int)DB::setting('candidate_limit',200))),'contract_version'=>SABRI_FILE26_CONTRACT_VERSION);
		$provided=apply_filters('sabri_file26_semantic_candidates',null,$request);if(is_wp_error($provided)||!is_array($provided)){$out['status']='degraded';return$out;}
		$scores=array();foreach(array_slice($provided,0,200) as $candidate){if(!is_array($candidate)||empty($candidate['key'])||!preg_match('/^[a-f0-9]{64}$/',(string)$candidate['key'])){continue;}$scores[(string)$candidate['key']]=isset($candidate['score'])?min(1,max(0,(float)$candidate['score'])):0.0;}
		if(!$scores){$out['status']='active';return$out;}$keys=array_keys($scores);$placeholders=implode(',',array_fill(0,count($keys),'%s'));$documents=DB::table('documents');$connectors=DB::table('connectors');$rows=$wpdb->get_results($wpdb->prepare("SELECT d.* FROM $documents d INNER JOIN $connectors c ON c.slug=d.connector_slug AND c.status='active' WHERE d.canonical_key IN ($placeholders)",$keys),ARRAY_A);if(null===$rows&&!empty($wpdb->last_error)){return new \WP_Error('file26_semantic_candidate_read_failed','Semantic candidate eligibility could not be verified safely.',array('status'=>503,'trace_id'=>$trace));}
		foreach((array)$rows as $row){$row=$this->hydrate_row($row);if(!$this->eligible_row($row,$audience,$filters,$locale)){continue;}$row['_semantic_score']=$scores[$row['canonical_key']];$out['rows'][]=$row;}$out['status']='active';return$out;
	}

	private function eligible_row(array $row,array $audience,array $filters,$locale){
		if(!in_array($row['state'],array('published','active','corrected','retracted'),true)||in_array($row['safety_class'],array('blocked','restricted'),true)){return false;}if(!$this->security->can_view_visibility($row['visibility'],$audience,$row['payload'])||!$this->connectors->can_view($row['connector_slug'],$row,$audience)){return false;}
		if($locale&&!in_array($row['locale'],array($locale,substr($locale,0,2),'und'),true)){return false;}$direct=array('entity_type','country','location','availability');foreach($direct as $field){if(!empty($filters[$field])&&(string)$row[$field]!== (string)$filters[$field]){return false;}}if(!empty($filters['connector'])&&(string)$row['connector_slug']!==(string)$filters['connector']){return false;}if(!empty($filters['domain'])&&(string)$row['domain_name']!==(string)$filters['domain']){return false;}if(!empty($filters['language'])&&(string)$row['locale']!==(string)$filters['language']){return false;}if(!empty($filters['author'])&&(string)$row['author_key']!==(string)$filters['author']){return false;}if(!empty($filters['topic'])&&!in_array((string)$filters['topic'],(array)$row['topic_ids_array'],true)){return false;}if(!empty($filters['date_from'])&&(!empty($row['freshness_at'])?substr($row['freshness_at'],0,10):'0000-00-00')<$filters['date_from']){return false;}if(!empty($filters['date_to'])&&!empty($row['freshness_at'])&&substr($row['freshness_at'],0,10)>$filters['date_to']){return false;}return true;
	}

	private function dedupe_ranked(array $rows){$seen=array();$out=array();foreach($rows as $row){$url=isset($row['canonical_url'])?untrailingslashit(strtolower((string)$row['canonical_url'])):'';$key=$url?'url:'.hash('sha256',$url):'key:'.$row['canonical_key'];if(isset($seen[$key])){continue;}$seen[$key]=true;$out[]=$row;}return$out;}

	private function apply_graph_relationship_scores(array $rows){global $wpdb;if(count($rows)<2){return$rows;}$index=array();foreach($rows as $position=>$row){$index[$row['canonical_key']]=$position;}$keys=array_keys($index);$counts=array_fill_keys($keys,0);$seen=array();$edge_table=DB::table('edges');foreach(array_chunk($keys,200) as $chunk){$placeholders=implode(',',array_fill(0,count($chunk),'%s'));$args=array_merge($chunk,$chunk,array(5000));$sql=$wpdb->prepare("SELECT edge_uuid,source_key,target_key FROM $edge_table WHERE state='active' AND visibility='public' AND (source_key IN ($placeholders) OR target_key IN ($placeholders)) ORDER BY edge_uuid LIMIT %d",$args);$edges=$wpdb->get_results($sql,ARRAY_A);if(null===$edges&&!empty($wpdb->last_error)){return new \WP_Error('file26_graph_signal_read_failed','Knowledge-graph ranking signal could not be read safely.',array('status'=>503));}foreach((array)$edges as $edge){if(isset($seen[$edge['edge_uuid']])){continue;}$seen[$edge['edge_uuid']]=true;if(isset($index[$edge['source_key']],$index[$edge['target_key']])){$counts[$edge['source_key']]++;$counts[$edge['target_key']]++;}}}foreach($counts as $key=>$count){$position=$index[$key];$rows[$position]['payload']['relationship_score']=min(1.0,$count/5);$rows[$position]['payload']['graph_relation_count']=min(1000,(int)$count);}return$rows;}
	private function hydrate_row(array $row){$row['payload']=json_decode(isset($row['payload'])?$row['payload']:'',true);$row['payload']=is_array($row['payload'])?$row['payload']:array();$row['topic_ids_array']=json_decode(isset($row['topic_ids'])?$row['topic_ids']:'',true);$row['topic_ids_array']=is_array($row['topic_ids_array'])?$row['topic_ids_array']:array();return$row;}
	private function sanitize_filters($filters){if(!is_array($filters)){return array();}$clean=array();foreach(array('entity_type','country','location','availability','connector','domain','topic','sort','language') as $key){if(!empty($filters[$key])){$clean[$key]='language'===$key?substr(sanitize_text_field($filters[$key]),0,20):sanitize_key($filters[$key]);}}if(!empty($filters['author'])){$clean['author']=substr(sanitize_text_field($filters['author']),0,191);}foreach(array('date_from','date_to') as $date_key){if(!empty($filters[$date_key])&&preg_match('/^\d{4}-\d{2}-\d{2}$/',$filters[$date_key])){$clean[$date_key]=$filters[$date_key];}}return$clean;}
	private function to_result(array $row,$query){$payload=is_array($row['payload'])?$row['payload']:array();unset($payload['download_url']);$actions=array('open'=>array('url'=>$row['canonical_url'],'label'=>__('Open','sabri-file26'),'icon'=>'external'));return array('key'=>$row['canonical_key'],'entity_type'=>$row['entity_type'],'title'=>$row['title'],'excerpt'=>$row['excerpt'],'url'=>$row['canonical_url'],'locale'=>$row['locale'],'state'=>$row['state'],'author_key'=>$row['author_key'],'topics'=>$row['topic_ids_array'],'country'=>$row['country'],'location'=>$row['location'],'availability'=>$row['availability'],'score'=>isset($row['_score'])?(float)$row['_score']:0.0,'explanation_codes'=>$this->explanation_codes($row,$query),'doctor_tier'=>'doctor'===$row['entity_type']?$this->ranking->doctor_tier($payload):null,'payload'=>$payload,'actions'=>$actions);}
	private function explanation_codes(array $row,$query){$codes=array('query_relevance','policy_'.sanitize_key($this->ranking->policy_version()));foreach($this->normalizer->phrases($query) as $phrase){if(false!==$this->strpos($row['normalized_title'],$phrase)||false!==$this->strpos($row['normalized_body'],$phrase)){$codes[]='exact_phrase';break;}}if((float)$row['authority_score']>=0.7){$codes[]='verified_authority';}if((float)$row['quality_score']>=0.7){$codes[]='source_quality';}if(!empty($row['_semantic_score'])){$codes[]='semantic_relevance';}if(!empty($row['payload']['relationship_score'])){$codes[]='knowledge_graph_relation';}if(in_array($row['state'],array('corrected','retracted'),true)){$codes[]='status_disclosed';}return array_values(array_unique($codes));}
	private function facets_from_rows(array $rows){$facets=array('entity_type'=>array(),'country'=>array(),'locale'=>array(),'availability'=>array(),'topic'=>array());foreach($rows as $row){foreach(array('entity_type','country','locale','availability') as $field){$value=isset($row[$field])?(string)$row[$field]:'';if(''!==$value){$facets[$field][$value]=isset($facets[$field][$value])?$facets[$field][$value]+1:1;}}foreach(isset($row['topic_ids_array'])?$row['topic_ids_array']:array() as $topic){$topic=sanitize_text_field($topic);if($topic){$facets['topic'][$topic]=isset($facets['topic'][$topic])?$facets['topic'][$topic]+1:1;}}}foreach($facets as &$values){arsort($values);}unset($values);return$facets;}

	private function record_metric($query,$locale,$count,$trace,$latency_ms){$sensitive=$this->security->contains_sensitive_query($query);$metric=$count?'search_with_results':'search_zero_result';$result=$this->record_operational_metric($metric,$locale,1,max(0,(float)$latency_ms),$sensitive?'sensitive_dropped':(''===$query?'browse':'search'));if(is_wp_error($result)){update_option('sabri_file26_last_search_metric_failure',array('at'=>DB::now(),'trace_id'=>$trace,'metric'=>$metric),false);return$result;}delete_option('sabri_file26_last_search_metric_failure');return true;}
	private function record_operational_metric($metric,$locale,$count=1,$sum=0,$class='operational'){global $wpdb;$metric=substr(sanitize_key($metric),0,96);$locale=substr(sanitize_text_field($locale),0,20);$bucket=hash_hmac('sha256',$class.'|'.$locale.'|'.gmdate('Y-m-d'),wp_salt('nonce'));$table=DB::table('metrics');$sql=$wpdb->prepare("INSERT INTO $table (metric_date,metric_key,bucket_hash,locale,count_value,sum_value,updated_at) VALUES (%s,%s,%s,%s,%d,%f,%s) ON DUPLICATE KEY UPDATE count_value=count_value+VALUES(count_value),sum_value=sum_value+VALUES(sum_value),updated_at=VALUES(updated_at)",gmdate('Y-m-d'),$metric,$bucket,$locale,max(0,(int)$count),max(0,(float)$sum),DB::now());$written=$wpdb->query($sql);if(false===$written){return new \WP_Error('file26_search_metric_write_failed','Search operational metric could not be persisted.',array('status'=>500));}return true;}
	private function strpos($haystack,$needle){return function_exists('mb_strpos')?mb_strpos((string)$haystack,(string)$needle,0,'UTF-8'):strpos((string)$haystack,(string)$needle);}
}
